from typing import Tuple

def gcd(a: int, b: int) -> int: ...
def lcm(a: int, b: int) -> int: ...
def extended_gcd(a: int, b: int) -> Tuple[int, int, int]: ...
def gcd_many(*nums: int) -> int: ...
def lcm_many(*nums: int) -> int: ...
